import PaymentForm from '@/_components/paymentPage/PaymentForm';

export const metadata = {
  title: 'Eventry - Payment',
  description: 'Generated by create next app',
};

export default function PaymentPage() {
  return (
    <section className="container">
      <div className="bg-[#242526] p-6 rounded-lg max-w-xl mx-auto my-12">
        <h2 className="font-bold text-xl mb-8">Payment Details</h2>
        <PaymentForm />
      </div>
    </section>
  );
}
