import EventList from '@/_components/homePage/EventList';
import EventPageHeader from '@/_components/homePage/EventPageHeader';

export const metadata = {
  title: 'Eventry - Home',
  description: 'Generated by create next app',
};

export default function Home() {
  return (
    <section className="container py-8">
      <EventPageHeader />
      <EventList />
    </section>
  );
}
