import EventDetails from '@/_components/detailsPage/EventDetails';
import EventVenue from '@/_components/detailsPage/EventVenue';
import Hero from '@/_components/detailsPage/Hero';

export const metadata = {
  title: 'Eventry - Google I/O Extended',
  description: 'Generated by create next app',
};

export default function EventDetailsPage() {
  return (
    <>
      <Hero />
      <section className="container">
        <div className="grid grid-cols-5 gap-12 my-12">
          <EventDetails />
          <EventVenue />
        </div>
      </section>
    </>
  );
}
